version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
